Workflow fixed

diff --git a/.github/workflows/registry-e2e-tests.yaml b/.github/workflows/registry-e2e-tests.yaml
--- a/.github/workflows/registry-e2e-tests.yaml
+++ b/.github/workflows/registry-e2e-tests.yaml
@@ -2,10 +2,10 @@ name: Run Connector E2E Tests (staging)
 
 on:
   pull_request:
+    types: [opened, synchronize, reopened, labeled]
     branches: [main]
     paths:
       - registry/**
-    
 
 jobs:
   setup-e2e:
@@ -43,7 +43,7 @@ jobs:
       - name: Setup Go
         uses: actions/setup-go@v4
         with:
-          go-version: 1.21.x
+          go-version: 1.2.4
 
       - name: Get the list of e2e tests to run
         id: e2e-test-matrix
@@ -52,9 +52,21 @@ jobs:
         run: |
           mv changed_files.json registry-automation/changed_files.json
           cd registry-automation
-          MATRIX_JSON=$(go run main.go e2e)
+          MATRIX_JSON=$(go run main.go e2e changed)
           echo "$MATRIX_JSON"
           echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"
+
+      - name: Check if connector is published to staging
+        id: check-connector-publish-status
+        run: |
+          LABELS='${{ toJSON(github.event.pull_request.labels.*.name) }}'
+          REQUIRED_LABEL="connector-staging-deploy-success"
+          if echo "$LABELS" | jq -e 'contains(["'"$REQUIRED_LABEL"'"])' > /dev/null; then
+            echo "Connector published to staging!"
+          else
+            echo "Error: Connector is not yet published to staging. This Job will automatically run again once the connector is published to staging."
+            exit 1
+          fi
 
   e2e-tests:
     needs: setup-e2e
@@ -62,15 +74,13 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        tasks: ${{ fromJSON(needs.setup-e2e.outputs.matrix) }}
+        task: ${{ fromJSON(needs.setup-e2e.outputs.matrix) }}
     env:
-      SELECTOR_PATTERN: ${{ matrix.tasks.selector_pattern }}
-      CONNECTOR_VERSION: ${{ matrix.tasks.connector_version }}
       CLI_TAG: latest-staging
     steps:
       - name: test
         run: |
-          echo "Running e2e tests for ${{ needs.setup-e2e.outputs.matrix}}"
+          echo "Running e2e tests for ${{ matrix.task }}"
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
@@ -84,5 +94,7 @@ jobs:
         env:
           HASURA_DDN_PAT: WSM4cGM1ChBIIykOHWRVv3rRsXwN7EdfK83g8xHE36MCUaXwmTRZccQYcMKx9pWd
         run: |
+          jq '[.]' ${{ matrix.task }} > test-job.json
+          export TEST_JOB_FILE=test-job.json
           bun install
           bun run start-ndc
